### PR TITLE
Add function to list all metric names from default set

### PR DESCRIPTION
**Pull request by sequix**

### CODE REVIEW

**Comment by vtolstov** [comment]
looks fine

**Review by hagen1778 — APPROVED** [review]
LGTM

**Comment by amenzhinsky** [comment]
Probably that's a separate issue, but why not to export `defaultSet` => `DefaultSet`, in some cases it would be handy.

**Review by valyala — APPROVED** [review]

**Comment by valyala** [comment]
@sequix , thanks for the pull request!

> why not to export defaultSet => DefaultSet, in some cases it would be handy.

@amenzhinsky , could you provide such cases?

**Comment by amenzhinsky** [comment]
@valyala this is just nice to have in cases when you'd like to configure to use the default or a custom one

https://github.com/amenzhinsky/grpcmetrics/blob/main/metrics.go#L17-L22

**Pull request merged**
