### PR TITLE
Add metrics.Close() and metrics.Set{}.Close()

### LINKED ISSUE #38: Introduce a `Close` method that pushes metrics one last time.
When you use the `InitPush` method to push metrics from a job, not all metrics get pushed. 

This specifically has to do with metrics that are pushed just before a job is terminated. An example of such a metric could be how long a job took to process. Since by the time this metric is pushed, there is never a last metric push, it never gets sent to a cluster. 

A solution could be to introduce a `Close` method perhaps compatible with `io.Closer` to push all metrics one last time. before a job is killed.

### PR DESCRIPTION
**Pull request by bubunyo**
This PR fixes #38

### CODE REVIEW

**Comment by bubunyo** [comment]
these changes work well in production. FYI.

**Comment by bubunyo** [comment]
> I don't thing Close() method should be global.
> It is better to change InitPush method signature to return a new object that can be stopped afterwards. This approach should be more flexible for various scenarios, despite the signature change (breaks backward compatibility)

That was my initial though and implementation as can be seen in this PR which i later closed due to certain issues. 

`metrics.InitPush` is global and the way it works is that, it will only push all collection sets which are registered. the registered set is itself not exported, so to have a single entity that can be closed, you will have to create an enity just for that single purpose. But closing anything other that a Set is counter intuitive. So going by this library, you can just deregister the set, and it will cease collection. 

Also like you mentioned, breaking backwards compatibility was not a change i was keen on.

**Comment by hagen1778** [comment]
Thanks for feedback @bubunyo! These are valid points and I agree on most of them. However, I anticipate that such requests as [this](https://github.com/VictoriaMetrics/metrics/issues/38#issuecomment-1405084566) would happen more in future. Returning a struct and breaking compatibility now makes lib more flexible, as we'd be able to extend sets with additional functionality if needed.
Would be nice to get feedback from @valyala as well.

**Comment by bubunyo** [comment]
> Thanks for feedback @bubunyo! These are valid points and I agree on most of them. However, I anticipate that such requests as [this](https://github.com/VictoriaMetrics/metrics/issues/38#issuecomment-1405084566) would happen more in future. Returning a struct and breaking compatibility now makes lib more flexible, as we'd be able to extend sets with additional functionality if needed.
> Would be nice to get feedback from @valyala as well.

true, but this would mean you would have to introduce more changes beyond the scope of this PR to make such a path viable. I believe InitPush should be a method on tests and not a global method, that will make a lot of other things way easier.

**Comment by valyala** [comment]
Closing this pull request, since the functionality that is needed for canceling the periodic metrics push and for sending metrics the last time is already available starting from the tag [v1.27.0](https://github.com/VictoriaMetrics/metrics/tree/v1.27.0). See [this comment](https://github.com/VictoriaMetrics/metrics/issues/38#issuecomment-1861797239) for more details.

**Pull request closed without merging**
